version: "3"
services:
  prestashop:
    image: prestashop/prestashop
    ports:
      - 8181:80
    volumes:
      - ./srv/Configs/PrestaShop/src:/var/www/html
      - ./srv/Configs/PrestaShop/src/modules:/var/www/html/modules
      - ./srv/Configs/PrestaShop/src/themes:/var/www/html/themes
      - ./srv/Configs/PrestaShop/src/override:/var/www/html/override
    environment:
      - PS_DEV_MODE=1
      - DB_USER=admin
      - DB_PASSWD=Manuel5897-
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=0
